name: tattoo_manager
description: TattooManager App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  faker:
  mocktail:
  http:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true




